version: '3.3'

services:

  server:
    container_name: nginx
    restart: always # 重启策略: 容器退出时总是重启容器
    build:
      context: . # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./Dockerfile
    ports:
      - "8090:80"
